service: nestjs-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 300
  environment:
    DB_URL: mongodb://127.0.0.1:27017
    DB_NAME: nest-lambda
    SMTP_HOST: smtp.gmail.com
    SMTP_PORT: 587
    SMTP_USER: example@gmail.com
    SMTP_PASSWORD: password
    SMTP_EMAIL_FROM: youremail@gmail.com
    SMTP_EMAIL_TO: toemail@gmail.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${self:service}-test-bucket"
        - "arn:aws:s3:::${self:service}-test-bucket/*"

custom:
  bucketName: ${self:service}-test-bucket

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
  cronJob:
    handler: src/cron.handler
    events: 
      - schedule: cron(59 23 * * ? *) # Run at 11:59 PM daily
  s3Trigger:
    handler: src/s3Trigger.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}

package:
  exclude:
    - node_modules/**
