service: nestjs-lambda
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  timeout: 300
  environment:
    DB_URL: ${env:DB_URL}
    DB_USER: ${env:DB_USER}
    DB_PW: ${env:DB_PW}
    DB_NAME: ${env:DB_NAME}
    SMTP_HOST: ${env:SMTP_HOST}
    SMTP_PORT: ${env:SMTP_PORT}
    SMTP_USER: ${env:SMTP_USER}
    SMTP_PASSWORD: ${env:SMTP_PASSWORD}
    SMTP_EMAIL_FROM: ${env:SMTP_EMAIL_FROM}
    SMTP_EMAIL_TO: ${env:SMTP_EMAIL_TO}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${self:service}-test-bucket"
        - "arn:aws:s3:::${self:service}-test-bucket/*"

custom:
  bucketName: ${self:service}-test-bucket

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
  cronJob:
    handler: src/cron.handler
    events: 
      - schedule: cron(59 23 * * ? *) # Run at 11:59 PM daily
  s3Trigger:
    handler: src/s3Trigger.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}

package:
  exclude:
    - node_modules/**
